# Generated by Django 3.0.3 on 2020-05-30 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0002_auto_20200530_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdatafilename',
            name='file_path',
            field=models.FilePathField(null=True, verbose_name='File Path on server'),
        ),
        migrations.AlterField(
            model_name='serverdatafilename',
            name='server_dataset_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microimprocessing.ServerDatasetPath'),
        ),
    ]
