# Generated by Django 3.0.3 on 2020-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0003_auto_20200530_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='file_path',
            field=models.FilePathField(path='C:\\Users\\Jirik\\data', verbose_name='File Path on server'),
        ),
    ]
