# Generated by Django 3.0.3 on 2020-05-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0004_auto_20200530_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatasetpath',
            name='server_dataset_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\Jirik\\data', verbose_name='Path to dataset on server'),
        ),
    ]
