# Generated by Django 3.0.3 on 2020-06-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0006_auto_20200530_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='file_path',
            field=models.FilePathField(path='C:\\Users\\Jirik\\data\\medical\\orig\\Scaffan-analysis', recursive=True, verbose_name='File Path on server'),
        ),
        migrations.AlterField(
            model_name='serverdatasetpath',
            name='server_dataset_path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='C:\\Users\\Jirik\\data\\medical\\orig\\Scaffan-analysis', verbose_name='Path to dataset on server'),
        ),
    ]
