# Generated by Django 3.0.3 on 2020-06-07 13:27
# import microimprocessing.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0007_auto_20200607_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdatafilename',
            name='file_path',
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='annotationfile',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Annotation File'),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to='image_preview/'),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='imagefile',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Uploaded File'),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='imagefile_path',
            field=models.FilePathField(blank=True, path='C:\\Users\\Jirik\\data\\medical\\orig\\Scaffan-analysis', recursive=True, verbose_name='File Path'),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='outputdir',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
