# Generated by Django 3.0.3 on 2020-06-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0008_auto_20200607_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
