# Generated by Django 3.0.3 on 2020-06-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0009_auto_20200607_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdatafilename',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='serverdatafilename',
            name='server_dataset_path',
        ),
    ]
