# Generated by Django 3.0.7 on 2020-06-13 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microimprocessing', '0010_auto_20200607_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdatafilename',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='thumbnail',
            field=models.FilePathField(blank=True, verbose_name='Thumbnail File'),
        ),
    ]
