# Generated by Django 3.0.7 on 2020-06-13 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microimprocessing', '0011_auto_20200613_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
