# Generated by Django 3.0.7 on 2020-06-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0014_auto_20200613_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdatafilename',
            name='imagefile_path',
        ),
    ]
