# Generated by Django 3.0.7 on 2020-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0015_remove_serverdatafilename_imagefile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='annotationfile',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Annotation File'),
        ),
        migrations.AlterField(
            model_name='serverdatafilename',
            name='imagefile',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Uploaded File'),
        ),
    ]
