# Generated by Django 3.0.7 on 2020-06-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0017_remove_serverdatafilename_image_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdatafilename',
            name='thumbnail',
        ),
    ]
