# Generated by Django 3.0.7 on 2020-06-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0018_remove_serverdatafilename_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdatafilename',
            name='thumbnail',
            field=models.FilePathField(blank=True, null=True, verbose_name='Thumbnail File'),
        ),
    ]
