# Generated by Django 3.0.7 on 2020-06-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0019_serverdatafilename_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdatafilename',
            name='thumbnail',
        ),
    ]
