# Generated by Django 3.0.7 on 2020-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0020_remove_serverdatafilename_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdatafilename',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thumbnail File'),
        ),
    ]
