# Generated by Django 3.0.7 on 2020-06-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0021_serverdatafilename_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverdatafilename',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='preview',
            field=models.ImageField(blank=True, upload_to='cellimage/'),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='preview_pixelsize_mm',
            field=models.FloatField(blank=True, default=0.1, verbose_name='Preview Pixelsize [mm]'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LobuleCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_mm', models.FloatField(verbose_name='X [mm]')),
                ('y_mm', models.FloatField(verbose_name='Y [mm]')),
                ('server_datafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microimprocessing.ServerDataFileName')),
            ],
        ),
    ]
