# Generated by Django 3.0.7 on 2020-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0022_auto_20200618_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='preview_pixelsize_mm',
            field=models.FloatField(blank=True, null=True, verbose_name='Preview Pixelsize [mm]'),
        ),
    ]
