# Generated by Django 3.0.7 on 2020-06-19 07:23

from django.db import migrations, models
import microimprocessing.models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0024_serverdatafilename_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='outputdir',
            field=models.CharField(blank=True, default=microimprocessing.models.get_output_dir, max_length=255),
        ),
    ]
