# Generated by Django 3.0.7 on 2020-06-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0025_auto_20200619_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_datafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microimprocessing.ServerDataFileName')),
            ],
        ),
    ]
