# Generated by Django 3.1.2 on 2020-10-12 11:02

from django.conf import settings
from django.db import migrations, models
import microimprocessing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microimprocessing', '0029_auto_20201006_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdatafilename',
            name='last_error_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='serverdatafilename',
            name='imagefile',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=microimprocessing.models.upload_to_unqiue_folder, verbose_name='Image File'),
        ),
        migrations.CreateModel(
            name='GDriveImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdrive_id', models.CharField(max_length=35)),
                ('gdir_id', models.CharField(max_length=35)),
                ('extension', models.CharField(max_length=10)),
                ('token', models.FilePathField(path='/webapps/scaffanweb_django/scaffanweb')),
                ('credentials', models.FilePathField(path='/webapps/scaffanweb_django/scaffanweb')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
