# Generated by Django 3.1.2 on 2021-02-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0030_auto_20201012_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdatafilename',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
