# Generated by Django 3.1.2 on 2021-02-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0031_serverdatafilename_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='cellimage/'),
        ),
    ]
