# Generated by Django 3.1.2 on 2021-02-21 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0032_auto_20210219_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitmapImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitmap_image', models.ImageField(upload_to='')),
                ('server_datafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microimprocessing.serverdatafilename')),
            ],
        ),
    ]
