# Generated by Django 3.1.2 on 2021-02-21 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0033_bitmapimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdatafilename',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='serverdatafilename',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Uploaded at'),
        ),
    ]
