# Generated by Django 3.1.7 on 2021-10-25 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microimprocessing', '0035_auto_20210313_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaffanParameterSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_parameters', models.TextField(default='{}', max_length=4000)),
                ('name', models.CharField(default='My Setting 1', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OverallMetric',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_used_version',
            field=models.CharField(default='0.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='text_parameters',
            field=models.TextField(default='{}', max_length=4000),
        ),
        migrations.AddField(
            model_name='serverdatafilename',
            name='scaffan_parameter_setup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='microimprocessing.scaffanparametersetup'),
        ),
    ]
