# Generated by Django 3.1.7 on 2022-06-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microimprocessing', '0036_auto_20211025_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdatafilename',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='cellimage/'),
        ),
    ]
