# Generated by Django 3.0.3 on 2020-05-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDatasetPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('server_dataset_path', models.FilePathField(allow_files=False, allow_folders=True, verbose_name='Path to dataset on server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerDataFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('processed', models.BooleanField()),
                ('processed_in_version', models.CharField(max_length=200)),
                ('server_dataset_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataimport.ServerDatasetPath')),
            ],
        ),
    ]
