# Generated by Django 3.0.3 on 2020-05-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0005_auto_20200530_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdatafilename',
            name='file_path',
            field=models.FilePathField(path='C:\\Users\\Jirik\\data', recursive=True, verbose_name='File Path on server'),
        ),
    ]
